"""Test_Second

Revision ID: 00dff229a3f3
Revises: 5145b6a32df4
Create Date: 2023-01-17 22:29:45.676113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00dff229a3f3'
down_revision = '5145b6a32df4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
