"""Added timestamp to messages

Revision ID: 2326199f5fd2
Revises: 6801bccd185d
Create Date: 2023-01-23 21:11:29.328209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2326199f5fd2'
down_revision = '6801bccd185d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_messages', sa.Column('time_stamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_messages', 'time_stamp')
    # ### end Alembic commands ###
