"""Test

Revision ID: 5145b6a32df4
Revises: 85f4c128b9d4
Create Date: 2023-01-17 22:20:03.790905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5145b6a32df4'
down_revision = '85f4c128b9d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
