"""Test_Third

Revision ID: 6801bccd185d
Revises: 00dff229a3f3
Create Date: 2023-01-17 22:30:20.170023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6801bccd185d'
down_revision = '00dff229a3f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
