"""Add Text Messages Table

Revision ID: 85f4c128b9d4
Revises: e33b171a6a46
Create Date: 2023-01-17 21:58:01.440696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f4c128b9d4'
down_revision = 'e33b171a6a46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_messages',
    sa.Column('message_sid', sa.String(), nullable=False),
    sa.Column('from_number', sa.String(), nullable=True),
    sa.Column('to_number', sa.String(), nullable=True),
    sa.Column('body', sa.String(length=1600), nullable=True),
    sa.PrimaryKeyConstraint('message_sid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_messages')
    # ### end Alembic commands ###
