"""Create user model

Revision ID: 892bb47d7725
Revises: 
Create Date: 2023-01-17 21:18:22.132868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892bb47d7725'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('phone_id', sa.String(), nullable=True),
    sa.Column('message_limit', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('is_paying', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
